[project]
name = "spotiapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "mysql-connector-python>=9.7.0",
    "pandas>=3.0.3",
    "pylast>=7.1.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "spotipy>=2.26.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
log_cli = true
log_cli_level = "INFO"

[project.scripts]
spotiapp-run = "spotiapp.main:main"

[tool.uv]
package = true